### ISSUE TITLE
wrong new releases icon

### ISSUE THREAD

**Issue by iambumblehead** [marella/material-design-icons#16]
wrong icon, [here](https://github.com/marella/material-design-icons/blob/main/svg/filled/new_releases.svg)
<img width="101" alt="Screen Shot 2022-12-21 at 9 41 53 PM" src="https://user-images.githubusercontent.com/2058705/209065286-dfeaa2b2-c3bf-42ff-81cc-4bca9dd427fb.png">

correct icon
<img width="142" alt="Screen Shot 2022-12-21 at 9 38 36 PM" src="https://user-images.githubusercontent.com/2058705/209065086-1b1e6f22-46b4-4b3d-a8b6-939738598f8d.png">

**Comment by marella** [comment]
The "wrong icon" posted above is from Material Icons (see original icon [here](https://fonts.google.com/icons?selected=Material+Icons+Outlined:new_releases:&icon.query=new_releases)) and the "correct icon" is from Material Symbols (see original icon [here](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:new_releases:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=new_releases)).
This repo only has Material Icons. For Material Symbols, see [marella/material-symbols](https://github.com/marella/material-symbols) (see [new_releases.svg](https://github.com/marella/material-symbols/blob/main/svg/400/sharp/new_releases.svg)).
Since there is an inconsistency between the original icon sets, please report it on [official repo](https://github.com/google/material-design-icons/issues).
