### ISSUE TITLE
Filled and outlined icons available in both folders

### ISSUE THREAD

**Issue by sschitcom** [marella/material-design-icons#20]
Why are icons like "chat_bubble.svg" (which is filled) and "chat_bubble_outline.svg" (which is outlined) both available in the outlined-folder and in the filled-folder? And not just the filled icon in the filled folder and the outlined icon in the outlined folder?

**Comment by marella** [comment]
Sorry for the late response. These icons are pulled from Google Fonts and both `chat_bubble` and `chat_bubble_outline` are listed under [filled](https://fonts.google.com/icons?icon.style=Filled&icon.set=Material+Icons&icon.query=chat_bubble) and [outlined](https://fonts.google.com/icons?icon.style=Outlined&icon.set=Material+Icons&icon.query=chat_bubble) styles.
I'm guessing Google might have created separate icons for filled and outlined so that they can be used with other styles: `rounded`, `sharp` etc.
Since this inconsistency is at the source, please report on [official repo](https://github.com/google/material-design-icons/issues).
