### ISSUE TITLE
Outlined favorite icon is filled

### ISSUE THREAD

**Issue by waterplea** [marella/material-design-icons#27]
The title says it's all :)

https://github.com/marella/material-design-icons/blob/main/svg/outlined/favorite.svg

**Comment by aimee-gm** [comment]
Maybe this is the icon you're after?

https://github.com/marella/material-design-icons/blob/main/svg/outlined/favorite_border.svg

Outlined doesn't refer to "This icon, but outlined instead of filled", but instead the `Outlined` style of material symbols from https://fonts.google.com/icons

<img width="291" alt="image" src="https://github.com/user-attachments/assets/e4e9321a-7b98-49da-ae14-fad56a235104">

**Comment by waterplea** [comment]
Yes, that icon works, but isn't it weird that outlined favorite is not outlined but filled? When I filter icons by outlined style I see it like that:

![image](https://github.com/user-attachments/assets/87ba7a5a-16db-4632-926c-b8ae559dd2cd)

**Comment by waterplea** [comment]
Oh, sorry, I understand what you mean. Thank you!
